//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lithnet.ResourceManagement.Client.ResourceManagementService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepresentationFailures", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Faults")]
    internal partial class RepresentationFailures : object
    {
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.AttributeRepresentationFailure[] attributeRepresentationFailuresField;
        
        private string correlationIdentifierField;
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.MessageRepresentationFailure[] messageRepresentationFailuresField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.AttributeRepresentationFailure[] attributeRepresentationFailures
        {
            get
            {
                return this.attributeRepresentationFailuresField;
            }
            set
            {
                this.attributeRepresentationFailuresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string correlationIdentifier
        {
            get
            {
                return this.correlationIdentifierField;
            }
            set
            {
                this.correlationIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.MessageRepresentationFailure[] messageRepresentationFailures
        {
            get
            {
                return this.messageRepresentationFailuresField;
            }
            set
            {
                this.messageRepresentationFailuresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttributeRepresentationFailure", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Faults")]
    internal partial class AttributeRepresentationFailure : object
    {
        
        private string additionalTextDetailsField;
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.AttributeFailureCode attributeFailureCodeField;
        
        private string attributeTypeField;
        
        private string attributeValueField;
        
        private string failureMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string additionalTextDetails
        {
            get
            {
                return this.additionalTextDetailsField;
            }
            set
            {
                this.additionalTextDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.AttributeFailureCode attributeFailureCode
        {
            get
            {
                return this.attributeFailureCodeField;
            }
            set
            {
                this.attributeFailureCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string attributeType
        {
            get
            {
                return this.attributeTypeField;
            }
            set
            {
                this.attributeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string attributeValue
        {
            get
            {
                return this.attributeValueField;
            }
            set
            {
                this.attributeValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string failureMessage
        {
            get
            {
                return this.failureMessageField;
            }
            set
            {
                this.failureMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageRepresentationFailure", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Faults")]
    internal partial class MessageRepresentationFailure : object
    {
        
        private string additionalTextDetailsField;
        
        private string failureMessageField;
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.MessageFailureCode messageFailureCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string additionalTextDetails
        {
            get
            {
                return this.additionalTextDetailsField;
            }
            set
            {
                this.additionalTextDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string failureMessage
        {
            get
            {
                return this.failureMessageField;
            }
            set
            {
                this.failureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.MessageFailureCode messageFailureCode
        {
            get
            {
                return this.messageFailureCodeField;
            }
            set
            {
                this.messageFailureCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttributeFailureCode", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Exceptions")]
    internal enum AttributeFailureCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChangeOperationIsNotSupported = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValueViolatesRegularExpression = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValueViolatesDataTypeFormat = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequiredValueIsMissing = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReferencedResourceIsMissing = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AttributeNameViolatesSchema = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResourceTypeViolatesSchema = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResourceTypeIsMissing = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemAttributeIsReadOnly = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValueViolatesUniqueness = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValueViolatesLimits = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 12,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageFailureCode", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Exceptions")]
    internal enum MessageFailureCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DialectIsNotSupported = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestMessageViolatesProtocol = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CultureIsNotEnabled = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CultureIsNotSupportedOnOperation = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestFailures", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Faults")]
    internal partial class RequestFailures : object
    {
        
        private string correlationIdentifierField;
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.EndpointReferenceType endpointReferenceField;
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.RequestAdministratorDetails requestAdministratorDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string correlationIdentifier
        {
            get
            {
                return this.correlationIdentifierField;
            }
            set
            {
                this.correlationIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.EndpointReferenceType endpointReference
        {
            get
            {
                return this.endpointReferenceField;
            }
            set
            {
                this.endpointReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.RequestAdministratorDetails requestAdministratorDetails
        {
            get
            {
                return this.requestAdministratorDetailsField;
            }
            set
            {
                this.requestAdministratorDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndpointReferenceType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSAddressing")]
    internal partial class EndpointReferenceType : object
    {
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.AttributedURIType addressFieldField;
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.MetadataType metadataFieldField;
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.ReferencePropertiesType referencePropertiesFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.AttributedURIType addressField
        {
            get
            {
                return this.addressFieldField;
            }
            set
            {
                this.addressFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.MetadataType metadataField
        {
            get
            {
                return this.metadataFieldField;
            }
            set
            {
                this.metadataFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.ReferencePropertiesType referencePropertiesField
        {
            get
            {
                return this.referencePropertiesFieldField;
            }
            set
            {
                this.referencePropertiesFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestAdministratorDetails", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Faults")]
    internal partial class RequestAdministratorDetails : object
    {
        
        private string additionalTextDetailsField;
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.FailedAttributes failedAttributesField;
        
        private string failureMessageField;
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.RequestFailureSource requestFailureSourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string additionalTextDetails
        {
            get
            {
                return this.additionalTextDetailsField;
            }
            set
            {
                this.additionalTextDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.FailedAttributes failedAttributes
        {
            get
            {
                return this.failedAttributesField;
            }
            set
            {
                this.failedAttributesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string failureMessage
        {
            get
            {
                return this.failureMessageField;
            }
            set
            {
                this.failureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.RequestFailureSource requestFailureSource
        {
            get
            {
                return this.requestFailureSourceField;
            }
            set
            {
                this.requestFailureSourceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttributedURIType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSAddressing")]
    internal partial class AttributedURIType : object
    {
        
        private string valueFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string valueField
        {
            get
            {
                return this.valueFieldField;
            }
            set
            {
                this.valueFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetadataType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSAddressing")]
    internal partial class MetadataType : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferencePropertiesType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSAddressing")]
    internal partial class ReferencePropertiesType : object
    {
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.LocaleReferencePropertyType localeReferencePropertyFieldField;
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.ResourceReferencePropertyType resourceReferencePropertyFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.LocaleReferencePropertyType localeReferencePropertyField
        {
            get
            {
                return this.localeReferencePropertyFieldField;
            }
            set
            {
                this.localeReferencePropertyFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.ResourceReferencePropertyType resourceReferencePropertyField
        {
            get
            {
                return this.resourceReferencePropertyFieldField;
            }
            set
            {
                this.resourceReferencePropertyFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocaleReferencePropertyType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    internal partial class LocaleReferencePropertyType : object
    {
        
        private string textFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string textField
        {
            get
            {
                return this.textFieldField;
            }
            set
            {
                this.textFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceReferencePropertyType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    internal partial class ResourceReferencePropertyType : object
    {
        
        private string textFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string textField
        {
            get
            {
                return this.textFieldField;
            }
            set
            {
                this.textFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FailedAttributes", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Faults")]
    internal partial class FailedAttributes : object
    {
        
        private string[] attributeTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string[] attributeType
        {
            get
            {
                return this.attributeTypeField;
            }
            set
            {
                this.attributeTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestFailureSource", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Exceptions")]
    internal enum RequestFailureSource : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManagementPolicyRule = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemConstraint = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Workflow = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResourceIsMissing = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DispatchRequestFailures", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Faults")]
    internal partial class DispatchRequestFailures : object
    {
        
        private string correlationIdentifierField;
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.DispatchRequestAdministratorDetails dispatchRequestAdministratorDetailsField;
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.EndpointReferenceType endpointReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string correlationIdentifier
        {
            get
            {
                return this.correlationIdentifierField;
            }
            set
            {
                this.correlationIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.DispatchRequestAdministratorDetails dispatchRequestAdministratorDetails
        {
            get
            {
                return this.dispatchRequestAdministratorDetailsField;
            }
            set
            {
                this.dispatchRequestAdministratorDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.EndpointReferenceType endpointReference
        {
            get
            {
                return this.endpointReferenceField;
            }
            set
            {
                this.endpointReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DispatchRequestAdministratorDetails", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Faults")]
    internal partial class DispatchRequestAdministratorDetails : object
    {
        
        private string additionalTextDetailsField;
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.DispatchRequestFailureSource dispatchRequestFailureSourceField;
        
        private string failureMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string additionalTextDetails
        {
            get
            {
                return this.additionalTextDetailsField;
            }
            set
            {
                this.additionalTextDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.DispatchRequestFailureSource dispatchRequestFailureSource
        {
            get
            {
                return this.dispatchRequestFailureSourceField;
            }
            set
            {
                this.dispatchRequestFailureSourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string failureMessage
        {
            get
            {
                return this.failureMessageField;
            }
            set
            {
                this.failureMessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DispatchRequestFailureSource", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Exceptions")]
    internal enum DispatchRequestFailureSource : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServiceIsStopping = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IdentityIsNotFound = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlternateEndpointNotSupported = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidResourceIdentifier = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Synchronization = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActionProcessor = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndpointFailures", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Faults")]
    internal partial class EndpointFailures : object
    {
        
        private string correlationIdentifierField;
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.EndpointAdministratorDetails endpointAdministratorDetailsField;
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.EndpointReferenceType endpointReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string correlationIdentifier
        {
            get
            {
                return this.correlationIdentifierField;
            }
            set
            {
                this.correlationIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.EndpointAdministratorDetails endpointAdministratorDetails
        {
            get
            {
                return this.endpointAdministratorDetailsField;
            }
            set
            {
                this.endpointAdministratorDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.EndpointReferenceType endpointReference
        {
            get
            {
                return this.endpointReferenceField;
            }
            set
            {
                this.endpointReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndpointAdministratorDetails", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Faults")]
    internal partial class EndpointAdministratorDetails : object
    {
        
        private string additionalTextDetailsField;
        
        private string failureMessageField;
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.HealthFailureSource healthFailureSourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string additionalTextDetails
        {
            get
            {
                return this.additionalTextDetailsField;
            }
            set
            {
                this.additionalTextDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string failureMessage
        {
            get
            {
                return this.failureMessageField;
            }
            set
            {
                this.failureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.HealthFailureSource healthFailureSource
        {
            get
            {
                return this.healthFailureSourceField;
            }
            set
            {
                this.healthFailureSourceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HealthFailureSource", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "Exceptions")]
    internal enum HealthFailureSource : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnonymousInteractionRequiredFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    internal partial class AnonymousInteractionRequiredFault : object
    {
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.InteractiveWorkflowAddress[] endpointAddressesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.InteractiveWorkflowAddress[] endpointAddresses
        {
            get
            {
                return this.endpointAddressesField;
            }
            set
            {
                this.endpointAddressesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InteractiveWorkflowAddress", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    internal partial class InteractiveWorkflowAddress : object
    {
        
        private string[] endpointAddressesField;
        
        private System.Guid instanceIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string[] endpointAddresses
        {
            get
            {
                return this.endpointAddressesField;
            }
            set
            {
                this.endpointAddressesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid instanceId
        {
            get
            {
                return this.instanceIdField;
            }
            set
            {
                this.instanceIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationRequiredFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    internal partial class AuthenticationRequiredFault : object
    {
        
        private string securityTokenServiceAddressFieldField;
        
        private System.Nullable<bool> userLockedOutField;
        
        private System.Nullable<bool> userRegisteredField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string securityTokenServiceAddressField
        {
            get
            {
                return this.securityTokenServiceAddressFieldField;
            }
            set
            {
                this.securityTokenServiceAddressFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Nullable<bool> userLockedOut
        {
            get
            {
                return this.userLockedOutField;
            }
            set
            {
                this.userLockedOutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Nullable<bool> userRegistered
        {
            get
            {
                return this.userRegisteredField;
            }
            set
            {
                this.userRegisteredField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.AuthorizationRequiredFault))]
    internal partial class RequestFault : object
    {
        
        private Lithnet.ResourceManagement.Client.ResourceManagementService.EndpointReferenceType endpointReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Lithnet.ResourceManagement.Client.ResourceManagementService.EndpointReferenceType endpointReference
        {
            get
            {
                return this.endpointReferenceField;
            }
            set
            {
                this.endpointReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorizationRequiredFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    internal partial class AuthorizationRequiredFault : Lithnet.ResourceManagement.Client.ResourceManagementService.RequestFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataRequiredFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSTransfer")]
    internal partial class DataRequiredFault : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CannotProcessFilterFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    internal partial class CannotProcessFilterFault : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupportedDialect", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSEnumeration")]
    internal partial class SupportedDialect : object
    {
        
        private string textFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string textField
        {
            get
            {
                return this.textFieldField;
            }
            set
            {
                this.textFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidExpirationTimeFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    internal partial class InvalidExpirationTimeFault : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnsupportedExpirationTypeFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    internal partial class UnsupportedExpirationTypeFault : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidEnumerationContextFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.ResourceManagement.WebServices." +
        "WSResourceManagement")]
    internal partial class InvalidEnumerationContextFault : object
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/2006/04/mex", ConfigurationName="Lithnet.ResourceManagement.Client.ResourceManagementService.IMetadataExchange")]
    internal interface IMetadataExchange
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Get", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/GetResponse")]
        System.ServiceModel.Channels.Message Get(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Get", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/GetResponse")]
        System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> GetAsync(System.ServiceModel.Channels.Message request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal interface IMetadataExchangeChannel : Lithnet.ResourceManagement.Client.ResourceManagementService.IMetadataExchange, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal partial class MetadataExchangeClient : System.ServiceModel.ClientBase<Lithnet.ResourceManagement.Client.ResourceManagementService.IMetadataExchange>, Lithnet.ResourceManagement.Client.ResourceManagementService.IMetadataExchange
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MetadataExchangeClient() : 
                base(MetadataExchangeClient.GetDefaultBinding(), MetadataExchangeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MetadataExchangeHttpBinding_IMetadataExchange.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MetadataExchangeClient(EndpointConfiguration endpointConfiguration) : 
                base(MetadataExchangeClient.GetBindingForEndpoint(endpointConfiguration), MetadataExchangeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MetadataExchangeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MetadataExchangeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MetadataExchangeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MetadataExchangeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MetadataExchangeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.ServiceModel.Channels.Message Get(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.Get(request);
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> GetAsync(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.GetAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MetadataExchangeHttpBinding_IMetadataExchange))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MetadataExchangeHttpBinding_IMetadataExchange))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5725/ResourceManagementService/MEX");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MetadataExchangeClient.GetBindingForEndpoint(EndpointConfiguration.MetadataExchangeHttpBinding_IMetadataExchange);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MetadataExchangeClient.GetEndpointAddress(EndpointConfiguration.MetadataExchangeHttpBinding_IMetadataExchange);
        }
        
        public enum EndpointConfiguration
        {
            
            MetadataExchangeHttpBinding_IMetadataExchange,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/09/enumeration", ConfigurationName="Lithnet.ResourceManagement.Client.ResourceManagementService.Search")]
    internal interface Search
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/Enumerate", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/EnumerateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.CannotProcessFilterFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="CannotProcessFilter")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.SupportedDialect), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="FilterDialectRequestedUnavailable")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name="InvalidRepresentation", Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.InvalidExpirationTimeFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="InvalidExpirationTime")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.UnsupportedExpirationTypeFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="UnsupportedExpirationType")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        System.ServiceModel.Channels.Message Enumerate(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/Enumerate", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/EnumerateResponse")]
        System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> EnumerateAsync(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/Pull", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/PullResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name="InvalidRepresentation", Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.InvalidEnumerationContextFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="InvalidEnumerationContext")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        System.ServiceModel.Channels.Message Pull(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/Pull", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/PullResponse")]
        System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> PullAsync(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/Renew", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/RenewResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.UnsupportedExpirationTypeFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="UnsupportedExpirationType")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name="InvalidRepresentation", Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.InvalidEnumerationContextFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="InvalidEnumerationContext")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.InvalidExpirationTimeFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="InvalidExpirationTime")]
        System.ServiceModel.Channels.Message Renew(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/Renew", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/RenewResponse")]
        System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> RenewAsync(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/GetStatus", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/GetStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name="InvalidRepresentation", Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.InvalidEnumerationContextFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="InvalidEnumerationContext")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
        System.ServiceModel.Channels.Message GetStatus(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/GetStatus", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/GetStatusResponse")]
        System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> GetStatusAsync(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/Release", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/ReleaseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.InvalidEnumerationContextFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="InvalidEnumerationContext")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name="InvalidRepresentation", Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer")]
        System.ServiceModel.Channels.Message Release(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/Release", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/ReleaseResponse")]
        System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> ReleaseAsync(System.ServiceModel.Channels.Message request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal interface SearchChannel : Lithnet.ResourceManagement.Client.ResourceManagementService.Search, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal partial class SearchClient : System.ServiceModel.ClientBase<Lithnet.ResourceManagement.Client.ResourceManagementService.Search>, Lithnet.ResourceManagement.Client.ResourceManagementService.Search
    {
        
        public SearchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.ServiceModel.Channels.Message Enumerate(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.Enumerate(request);
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> EnumerateAsync(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.EnumerateAsync(request);
        }
        
        public System.ServiceModel.Channels.Message Pull(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.Pull(request);
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> PullAsync(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.PullAsync(request);
        }
        
        public System.ServiceModel.Channels.Message Renew(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.Renew(request);
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> RenewAsync(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.RenewAsync(request);
        }
        
        public System.ServiceModel.Channels.Message GetStatus(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.GetStatus(request);
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> GetStatusAsync(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.GetStatusAsync(request);
        }
        
        public System.ServiceModel.Channels.Message Release(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.Release(request);
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> ReleaseAsync(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.ReleaseAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer", ConfigurationName="Lithnet.ResourceManagement.Client.ResourceManagementService.Resource")]
    internal interface Resource
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Get", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/GetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name="InvalidRepresentation")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
        System.ServiceModel.Channels.Message Get(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Get", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/GetResponse")]
        System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> GetAsync(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Put", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/PutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.AnonymousInteractionRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="AnonymousInteractionRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name="InvalidRepresentation")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.AuthenticationRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="AuthenticationRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.AuthorizationRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="AuthorizationRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        System.ServiceModel.Channels.Message Put(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Put", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/PutResponse")]
        System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> PutAsync(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Delete", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/DeleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.AuthorizationRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="AuthorizationRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.AuthenticationRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="AuthenticationRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name="InvalidRepresentation")]
        System.ServiceModel.Channels.Message Delete(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Delete", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/DeleteResponse")]
        System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> DeleteAsync(System.ServiceModel.Channels.Message request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal interface ResourceChannel : Lithnet.ResourceManagement.Client.ResourceManagementService.Resource, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal partial class ResourceClient : System.ServiceModel.ClientBase<Lithnet.ResourceManagement.Client.ResourceManagementService.Resource>, Lithnet.ResourceManagement.Client.ResourceManagementService.Resource
    {
        
        public ResourceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.ServiceModel.Channels.Message Get(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.Get(request);
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> GetAsync(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.GetAsync(request);
        }
        
        public System.ServiceModel.Channels.Message Put(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.Put(request);
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> PutAsync(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.PutAsync(request);
        }
        
        public System.ServiceModel.Channels.Message Delete(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.Delete(request);
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> DeleteAsync(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer", ConfigurationName="Lithnet.ResourceManagement.Client.ResourceManagementService.ResourceFactory")]
    internal interface ResourceFactory
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Create", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/CreateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.DataRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="DataRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name="InvalidRepresentation")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.AuthorizationRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="AuthorizationRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.AuthenticationRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="AuthenticationRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lithnet.ResourceManagement.Client.ResourceManagementService.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
        System.ServiceModel.Channels.Message Create(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Create", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/CreateResponse")]
        System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> CreateAsync(System.ServiceModel.Channels.Message request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal interface ResourceFactoryChannel : Lithnet.ResourceManagement.Client.ResourceManagementService.ResourceFactory, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal partial class ResourceFactoryClient : System.ServiceModel.ClientBase<Lithnet.ResourceManagement.Client.ResourceManagementService.ResourceFactory>, Lithnet.ResourceManagement.Client.ResourceManagementService.ResourceFactory
    {
        
        public ResourceFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.ServiceModel.Channels.Message Create(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.Create(request);
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> CreateAsync(System.ServiceModel.Channels.Message request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
