//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lithnet.ResourceManagement.Client.ResourceManagementService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer", ConfigurationName="ResourceManagementService.Resource")]
    internal interface Resource {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Get", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/GetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="InvalidRepresentation")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        System.ServiceModel.Channels.Message Get(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Put", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/PutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.AnonymousInteractionRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="AnonymousInteractionRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="InvalidRepresentation")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.AuthorizationRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="AuthorizationRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.AuthenticationRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="AuthenticationRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
        System.ServiceModel.Channels.Message Put(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Delete", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/DeleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="InvalidRepresentation")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.AuthenticationRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="AuthenticationRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.AuthorizationRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="AuthorizationRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
        System.ServiceModel.Channels.Message Delete(System.ServiceModel.Channels.Message request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ResourceChannel : Lithnet.ResourceManagement.Client.ResourceManagementService.Resource, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class ResourceClient : System.ServiceModel.ClientBase<Lithnet.ResourceManagement.Client.ResourceManagementService.Resource>, Lithnet.ResourceManagement.Client.ResourceManagementService.Resource {
        
        public ResourceClient() {
        }
        
        public ResourceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResourceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ServiceModel.Channels.Message Get(System.ServiceModel.Channels.Message request) {
            return base.Channel.Get(request);
        }
        
        public System.ServiceModel.Channels.Message Put(System.ServiceModel.Channels.Message request) {
            return base.Channel.Put(request);
        }
        
        public System.ServiceModel.Channels.Message Delete(System.ServiceModel.Channels.Message request) {
            return base.Channel.Delete(request);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer", ConfigurationName="ResourceManagementService.ResourceFactory")]
    internal interface ResourceFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Create", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/CreateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.AuthorizationRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="AuthorizationRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.AuthenticationRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="AuthenticationRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSTransfer.DataRequiredFault), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="DataRequiredFault", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RepresentationFailures), Action = "http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name = "InvalidRepresentation")]
        System.ServiceModel.Channels.Message Create(System.ServiceModel.Channels.Message request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ResourceFactoryChannel : Lithnet.ResourceManagement.Client.ResourceManagementService.ResourceFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class ResourceFactoryClient : System.ServiceModel.ClientBase<Lithnet.ResourceManagement.Client.ResourceManagementService.ResourceFactory>, Lithnet.ResourceManagement.Client.ResourceManagementService.ResourceFactory {
        
        public ResourceFactoryClient() {
        }
        
        public ResourceFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResourceFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ServiceModel.Channels.Message Create(System.ServiceModel.Channels.Message request) {
            return base.Channel.Create(request);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/09/enumeration", ConfigurationName="ResourceManagementService.Search", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    internal interface Search {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/Enumerate", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/EnumerateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name="InvalidRepresentation", Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSEnumeration.SupportedDialect), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="FilterDialectRequestedUnavailable")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.InvalidExpirationTimeFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="InvalidExpirationTime")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.UnsupportedExpirationTypeFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="UnsupportedExpirationType")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.CannotProcessFilterFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="CannotProcessFilter")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
        System.ServiceModel.Channels.Message Enumerate(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/Pull", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/PullResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.InvalidEnumerationContextFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="InvalidEnumerationContext")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name="InvalidRepresentation", Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer")]
        System.ServiceModel.Channels.Message Pull(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/Renew", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/RenewResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.InvalidExpirationTimeFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="InvalidExpirationTime")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name="InvalidRepresentation", Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.UnsupportedExpirationTypeFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="UnsupportedExpirationType")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.InvalidEnumerationContextFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="InvalidEnumerationContext")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        System.ServiceModel.Channels.Message Renew(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/GetStatus", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/GetStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name="InvalidRepresentation", Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.InvalidEnumerationContextFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="InvalidEnumerationContext")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
        System.ServiceModel.Channels.Message GetStatus(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/Release", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/enumeration/ReleaseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.DispatchRequestFailures), Action="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess/fault", Name="UnwillingToPerform", Namespace="http://schemas.microsoft.com/2006/11/IdentityManagement/DirectoryAccess")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.WSResourceManagement.InvalidEnumerationContextFault), Action="http://schemas.xmlsoap.org/ws/2004/09/enumeration/fault", Name="InvalidEnumerationContext")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.EndpointFailures), Action="http://www.w3.org/2005/08/addressing/fault", Name="EndpointUnavailable", Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RepresentationFailures), Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/fault", Name="InvalidRepresentation", Namespace="http://schemas.xmlsoap.org/ws/2004/09/transfer")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.ResourceManagement.WebServices.Faults.RequestFailures), Action="http://schemas.microsoft.com/2006/11/ResourceManagement/fault", Name="PermissionDenied", Namespace="http://schemas.microsoft.com/2006/11/ResourceManagement")]
        System.ServiceModel.Channels.Message Release(System.ServiceModel.Channels.Message request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface SearchChannel : Lithnet.ResourceManagement.Client.ResourceManagementService.Search, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class SearchClient : System.ServiceModel.ClientBase<Lithnet.ResourceManagement.Client.ResourceManagementService.Search>, Lithnet.ResourceManagement.Client.ResourceManagementService.Search {
        
        public SearchClient() {
        }
        
        public SearchClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ServiceModel.Channels.Message Enumerate(System.ServiceModel.Channels.Message request) {
            return base.Channel.Enumerate(request);
        }
        
        public System.ServiceModel.Channels.Message Pull(System.ServiceModel.Channels.Message request) {
            return base.Channel.Pull(request);
        }
        
        public System.ServiceModel.Channels.Message Renew(System.ServiceModel.Channels.Message request) {
            return base.Channel.Renew(request);
        }
        
        public System.ServiceModel.Channels.Message GetStatus(System.ServiceModel.Channels.Message request) {
            return base.Channel.GetStatus(request);
        }
        
        public System.ServiceModel.Channels.Message Release(System.ServiceModel.Channels.Message request) {
            return base.Channel.Release(request);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/2006/04/mex", ConfigurationName="ResourceManagementService.IMetadataExchange", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    internal interface IMetadataExchange {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/ws/2004/09/transfer/Get", ReplyAction="http://schemas.xmlsoap.org/ws/2004/09/transfer/GetResponse")]
        System.ServiceModel.Channels.Message Get(System.ServiceModel.Channels.Message request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IMetadataExchangeChannel : Lithnet.ResourceManagement.Client.ResourceManagementService.IMetadataExchange, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class MetadataExchangeClient : System.ServiceModel.ClientBase<Lithnet.ResourceManagement.Client.ResourceManagementService.IMetadataExchange>, Lithnet.ResourceManagement.Client.ResourceManagementService.IMetadataExchange {
        
        public MetadataExchangeClient() {
        }
        
        public MetadataExchangeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MetadataExchangeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetadataExchangeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetadataExchangeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ServiceModel.Channels.Message Get(System.ServiceModel.Channels.Message request) {
            return base.Channel.Get(request);
        }
    }
}
